export const Codes = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    MOVED_PERMANENTLY: 301,
    FOUND: 301,
    NOT_MODIFIED: 304,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    ALREADY_EXIST: 409
};

export const CONSTANTS = {
   
    MYSQL_DATE_FORMAT:'YYYY-MM-DD',
    MYSQL_DATE_IN_FORMAT:'DD-MM-YYYY',
    MYSQL_DATE_TIME_FORMAT:'YYYY-MM-DD HH:mm:ss',
    MYSQL_TIME_FORMAT:'YYYY-MM-DD HH:mm:ss',
    STATUS_CODE:'statusCode',
    SITE_DATE_FORMAT:'DD/MM/YYYY',
    NOTIFICATION_TEMPLATE_005_ID:0,
    NOTIFICATION_TEMPLATE_000_ID:1,
    NOTIFICATION_TEMPLATE_002_ID:2,
    NOTIFICATION_TEMPLATE_003_ID:3,
    NOTIFICATION_TEMPLATE_004_ID:4,
    NOTIFICATION_TEMPLATE_010_ID:10,
    NOTIFICATION_TEMPLATE_006_ID:6,
    NOTIFICATION_TEMPLATE_007_ID:7,
    NOTIFICATION_TEMPLATE_008_ID:8,
    NOTIFICATION_TEMPLATE_011_ID:12,
    NOTIFICATION_TEMPLATE_012_ID:13,
    NOTIFICATION_TEMPLATE_013_ID:14,
    NOTIFICATION_TEMPLATE_014_ID:15,
    NOTIFICATION_TEMPLATE_016_ID:19,
    NOTIFICATION_TEMPLATE_020_ID:20,
    NOTIFICATION_TEMPLATE_021_ID:21,
    NOTIFICATION_TEMPLATE_022_ID:22,

    RESET_PASSWORD_TEMPLATE_ID:17,
    NOTIFICATION_INVITE_COLLEAGUE:18,
    LOGIN_SUCCESS:'Login request successfully.',
    ADMIN_FORGOT_PASSWORD_SUCCESS:'Please check the registered mail id we have sent a mail for change the password',
    FORGOT_PASSWORD_SUCCESS:'Sent verification code to your registered email id',
    EMAIL_SUCCESS_VERIFY:'Email address verified successfully',
    PASSWORD_RESET_SUCCESS:'Password changed successfully',
    USER_PASSWORD_RESET:'Password has changed please login again with new password',
    LOGOUT_SUCCESS:'Logout successful',
    USER_STATUS_UPDATE:'User actived successfully',
    ACCOUNT_DELETE_SUCCESS:'Account deleted successfully',
    EMAIL_CHANGE_SUCCESS:'Email address changed successfully please verify your new email address',
    INFORMATION_UPDATED:'Information updated successfully',
    PASSWORD_SUCCESS_VERIFY:'Password changed successfully',
    EMAIL_VERIFICATION_PENDING:'Your account verification is pending.',
    ACCOUNT_DELETED:'Account has been deleted',
    PASSWORD_DIFF:'New password must be different from old',
    USER_NOT_EXIST:'User does not exist',
    INCORRECT_EMAIL_PASSWORD:'Incorrect email address or password',
    INCORRECT_PASSWORD:'Password is incorrect',
    EMAIL_TAKEN:'Sorry! email address is already being used',
    EMAIL_IS_SAME:'New Email address is same as old',
    EMAIL_IS_ICORRECT:'Email address is not correct',
    RECORD_FOUND:'Record Found',
    RECORD_NOT_FOUND: 'No Record Found',
    EMAIL_ID_NOT_EXIST:'email id does not exist',
    PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
    INVALID_EMAIL_PASSWORD: 'Inavild email id and password.',
    EMAIL_ALREADY_EXIST:'Email address already exist',
    EMAIL_SENT_TO: 'Email sent to successfully.',
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
    OLD_PASSWORD_DOESNT_MATCH: "Old password doesn\'t match. Please try again.",
    SUCCESS: "Success",
    FAILED: "Failed",
    UNAUTHORIZED_ACCESS: 'Unauthorized Access.',
    USER_NOT_FOUND: "User not found.",
    AUTHENTICATION_FAILED: "Invalid credentials",
    COMPANY_ALREADY_EXIST:'Company already exist',
    DOMAIN_ALREADY_EXISTS: 'Domain already exists.',
    NOT_AN_ADMIN: 'You are not an admin. Only admin can perform this action.',
    NOT_A_MEMBER: 'Not a member, Only member can add colleague.',
    ALREADY_INVITED: 'User is already invited.',
    REQUIRED_FIELDS_ARE_MISSING: 'Required fields are missing.',
    SOMETHING_WENT_WRONG: 'Something went wrong! Please try again.',
    EVENT_ALREADY_EXISTS: 'This event already exist for this client and event provider.',
    USER_IS_PRIVATE: 'Sorry! User profile must be public to reset password.',
    NOT_A_CREATOR: 'Sorry! Only creator has this permission.',
    NOT_A_ADMIN_OR_STAFF: 'Only company admin or staff can perform this action.',
    IMPORTED_FILE_IS_NOT_VALID: "Imported file contains data which is not valid.", 
    BLANK_FILE_UPLOADED: "You have uploaded a blank file, Please recheck the file and try again.", 
    ONLY_EVENT_MANAGER_CAN_PERFORM_THIS_ACTION: "Sorry! Only event manager can perform this action.",
    TASK_SUCCESSFULLY_CREATED: "Task created successfully.", 
    TASK_SUCCESSFULLY_UPDATED: "Task updated successfully.",
    SENDCONFIRMATION: "Confirmation sent successfully.",
    TASK_SUCCESSFULLY_DELETED: "Task deleted successfully",
    NO_TASK_PERMISSION: "Sorry! You don't have permission to create this task.",
    NO_PERMISSION_TO_DELETE_TASK: "Sorry! You don't have permission to delete this task.",
    NO_PERMISSION_TO_VIEW_TASK: "Sorry! You don't have permission to view task for this function.",
    NO_PERMISSION_TO_UPDATE_TASK: "Sorry! You don't have permission to update the status of this task.",
    NO_TASK_FOUND_FOR_YOUR_COMPANY: "Sorry! We couldn't find any task for your company.",
    TASK_STATUS_UPDATED_SUCCESSFULLY: "Task status updated successfully.",
    ALREADY_COMPLETED: "Sorry! This task can not be deleted as it is already completed by some of the user.",
    NOT_AN_OWNER: "Sorry! Only the owner company can edit the task.",
    ASSIGNED_TO_CMP_NOT_IN_EVENT: "Permission Denied! Please choose different company from top menu to operate on task for this event."
};



